---
- name: Generate Access Key file
  file:
    path: /etc/passwd-s3fs
    mode: 0640
    state: touch
    owner: "{{fs_user}}"

# I strongly recommend to set these varibles using extra-vars in the command line
- name: Configuring Access
  lineinfile:
    path: /etc/passwd-s3fs
    line: "{{aws_access_key}}:{{aws_secret_key}}"
    mode: 0640
    owner: "{{fs_user}}"

